# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginmapa.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mwlogin(object):
    def setupUi(self, mwlogin):
        mwlogin.setObjectName("mwlogin")
        mwlogin.resize(338, 417)
        mwlogin.setMinimumSize(QtCore.QSize(338, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/senha.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mwlogin.setWindowIcon(icon)
        mwlogin.setAccessibleDescription("")
        mwlogin.setStyleSheet("background-color:rgb(115, 162, 191);")
        self.centralwidget = QtWidgets.QWidget(mwlogin)
        self.centralwidget.setObjectName("centralwidget")
        self.edtsenha = QtWidgets.QLineEdit(self.centralwidget)
        self.edtsenha.setGeometry(QtCore.QRect(70, 230, 221, 31))
        self.edtsenha.setStyleSheet("background-color: rgb(242, 242, 242);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"border-top-left-radius: 7px;\n"
"border-top-right-radius: 7px;\n"
"border-bottom-right-radius: 7px;\n"
"border-bottom-left-radius: 7px;")
        self.edtsenha.setMaxLength(15)
        self.edtsenha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.edtsenha.setObjectName("edtsenha")
        self.edtusuario = QtWidgets.QLineEdit(self.centralwidget)
        self.edtusuario.setGeometry(QtCore.QRect(70, 160, 221, 31))
        self.edtusuario.setStyleSheet("background-color: rgb(242, 242, 242);\n"
"font: 16pt \"\'Lato\', sans-serif\";\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    border-bottom-left-radius: 7px;")
        self.edtusuario.setMaxLength(15)
        self.edtusuario.setObjectName("edtusuario")
        self.lbliconsenha = QtWidgets.QLabel(self.centralwidget)
        self.lbliconsenha.setGeometry(QtCore.QRect(10, 220, 41, 41))
        self.lbliconsenha.setText("")
        self.lbliconsenha.setPixmap(QtGui.QPixmap("icons/senha.png"))
        self.lbliconsenha.setScaledContents(True)
        self.lbliconsenha.setObjectName("lbliconsenha")
        self.lblsenha = QtWidgets.QLabel(self.centralwidget)
        self.lblsenha.setGeometry(QtCore.QRect(70, 210, 51, 20))
        self.lblsenha.setStyleSheet("font: 12pt \"\'Lato\', sans-serif;\"\n"
"")
        self.lblsenha.setObjectName("lblsenha")
        self.lblusuario = QtWidgets.QLabel(self.centralwidget)
        self.lblusuario.setGeometry(QtCore.QRect(70, 130, 61, 31))
        self.lblusuario.setStyleSheet("font: 12pt \"\'Lato\', sans-serif;\"\n"
"")
        self.lblusuario.setObjectName("lblusuario")
        self.lbliconusuario = QtWidgets.QLabel(self.centralwidget)
        self.lbliconusuario.setGeometry(QtCore.QRect(10, 150, 47, 41))
        self.lbliconusuario.setText("")
        self.lbliconusuario.setPixmap(QtGui.QPixmap("icons/do-utilizador.png"))
        self.lbliconusuario.setScaledContents(True)
        self.lbliconusuario.setObjectName("lbliconusuario")
        self.btnentrar = QtWidgets.QPushButton(self.centralwidget)
        self.btnentrar.setGeometry(QtCore.QRect(100, 310, 131, 31))
        self.btnentrar.setStyleSheet("QPushButton{\n"
"    border: 2px;\n"
"    border-color: black;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-style: outset;\n"
"    background-color: rgb(59, 219, 0);\n"
"    font: 16pt \"\'Lato, sans-serif\";}\n"
"QPushButton:pressed{\n"
"    font: 16pt \"\'Lato, sans-serif\";\n"
"    border: 2px;\n"
"    border-color: #DBF227;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-style: outset;\n"
"    background-color: rgb(59, 219, 0);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/entrar.png"),  QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnentrar.setIcon(icon1)
        self.btnentrar.setObjectName("btnentrar")
        self.lbltitulo = QtWidgets.QLabel(self.centralwidget)
        self.lbltitulo.setGeometry(QtCore.QRect(100, 20, 221, 61))
        self.lbltitulo.setStyleSheet("color: rgb(219, 242, 39);\n"
"font: 63 24pt \"Open Sans Semibold\";")
        self.lbltitulo.setObjectName("lbltitulo")
        self.lblimagemglobo = QtWidgets.QLabel(self.centralwidget)
        self.lblimagemglobo.setGeometry(QtCore.QRect(20, 20, 61, 71))
        self.lblimagemglobo.setText("")
        self.lblimagemglobo.setPixmap(QtGui.QPixmap("icons/globo.png"))
        self.lblimagemglobo.setScaledContents(True)
        self.lblimagemglobo.setObjectName("lblimagemglobo")
        mwlogin.setCentralWidget(self.centralwidget)

        self.retranslateUi(mwlogin)
        QtCore.QMetaObject.connectSlotsByName(mwlogin)

    def retranslateUi(self, mwlogin):
        _translate = QtCore.QCoreApplication.translate
        mwlogin.setWindowTitle(_translate("mwlogin", "Login"))
        self.lblsenha.setText(_translate("mwlogin", "Senha"))
        self.lblusuario.setText(_translate("mwlogin", "Usuário"))
        self.btnentrar.setText(_translate("mwlogin", "Entrar"))
        self.lbltitulo.setText(_translate("mwlogin", "projeto mapa"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mwlogin = QtWidgets.QMainWindow()
    ui = Ui_mwlogin()
    ui.setupUi(mwlogin)
    mwlogin.show()
    sys.exit(app.exec_())
